### ISSUE TITLE
Projektstatus

### ISSUE THREAD

**Issue by pabay101** [ProPra16/programmierpraktikum-abschlussprojekt-something-normal-1#1]
Hallo zusammen,

außer der Readme wurde ja noch nichts hochgeladen. Ist diese Gruppe denn noch aktiv?

LG,
Paul

**Comment by LorcanMacKee** [comment]
Ja die Gruppe ist noch aktiv.
Gibt zur Zeit ein paar kleine organisatorische Probleme.

MFG
Luca
Am 10.07.2016 23:03 schrieb "KorrektorPaul" notifications@github.com:

Hallo zusammen,

außer der Readme wurde ja noch nichts hochgeladen. Ist diese Gruppe denn
noch aktiv?

LG,
Paul

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/ProPra16/programmierpraktikum-abschlussprojekt-something-normal-1/issues/1,
or mute the thread
https://github.com/notifications/unsubscribe/ALtcP6Frbh5aB0WP86tjPFvN8hOkyPPlks5qUV4UgaJpZM4JI6uD
.

**Comment by pabay101** [comment]
In dem Fall möchte ich mich einmal mit euch für 5-10 Minuten treffen, um einen Überblick zu erhalten, wie weit ihr seid.

**Comment by bendisposto** [comment]
Ich zitiere aus der Aufgabenstellung: "Die Entwicklung findet in Github statt, [...]". Davon sehe ich nichts. 
"Die Ergebnisse dieser Treffen sind in einem Protokoll festzuhalten. Die Protokolle müssen wie der Code in Github gepusht werden.", auch davon ist hier nichts zu sehen.

**Comment by LorcanMacKee** [comment]
Die organisatorischen Probleme wurden gelöst. 
Die Protokolle wurden hochgeladen und die Entwicklung des Projekts erfolgt nun wie vorgesehen über Github.

**Comment by bendisposto** [comment]
Travis geht noch nicht! Im Ilias ist das Problem in den Thread 
 Travis Java version "1.8.0_31

diskutiert worden

**Comment by LorcanMacKee** [comment]
Update:
Travis läuft wieder.
Jedoch bleibt TestResults nach dem compiling null. Dies versuchen wir gerade zu beheben.
An Tracking arbeite ich gerade noch.
